<?php

define('ITEM_INSERTED_SUCCESSFULLY', 0);
define('ITEM_INSERTED_FAILED', 1);

define('USER_CREATED_SUCCESSFULLY', 0);
define('USER_CREATE_FAILED', 1);
define('USER_ALREADY_EXISTED', 2);

define('QUERY_CREATED_SUCCESSFULLY', 0);
define('QUERY_CREATE_FAILED', 1);

define('STOCK_ADDED_SUCCESSFULLY', 0);
define('STOCK_ADDED_FAILED', 1);
?>